site_name: "stgacct02rmt" 
site_description: Azure Storage Account Template Documentation
site_url: https://portal.azure.com
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
  palette:
    primary: blue
    accent: light-blue

nav:
  - Home: index.md
  - Template Overview: template-overview.md
  - Azure Resource Configuration:
      - Storage Account: storage-account.md
      - Networking: networking.md
  - Deployment Guide: deployment-guide.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UKGH1
      
plugins:
  - techdocs-core
